import { User } from './types'

export const dummyUsers: User[] = [
  {
    name: 'John Smith',
    email: 'john.smith@example.com',
    type: 'influencer',
    createdAt: new Date('2024-01-15'),
    earnings: 15000,
    followers: 50000,
    engagement: 4.5,
    totalPosts: 120,
  },
  {
    name: 'Maria Garcia',
    email: 'maria.garcia@example.com',
    type: 'influencer',
    createdAt: new Date('2024-02-01'),
    earnings: 25000,
    followers: 75000,
    engagement: 5.2,
    totalPosts: 200,
  },
  {
    name: 'Alex Johnson',
    email: 'alex.j@example.com',
    type: 'user',
    createdAt: new Date('2024-01-10'),
    earnings: 0,
    followers: 0,
    engagement: 0,
    totalPosts: 0,
  },
  {
    name: 'Sophie Chen',
    email: 'sophie.chen@example.com',
    type: 'influencer',
    createdAt: new Date('2024-02-15'),
    earnings: 18000,
    followers: 60000,
    engagement: 4.8,
    totalPosts: 150,
  },
  {
    name: 'Mike Brown',
    email: 'mike.b@example.com',
    type: 'user',
    createdAt: new Date('2024-01-20'),
    earnings: 0,
    followers: 0,
    engagement: 0,
    totalPosts: 0,
  },
]
